services:
  frontend:
    build:
      dockerfile: ./Dockerfile-dev
      context: .
    volumes:
      - "litmy-node_modules:/app/node_modules"
      - ".:/app"
    ports:
      - "5173:5173"
volumes:
  litmy-node_modules:
